### ISSUE TITLE
Feature: Download All Episodes

### ISSUE THREAD

**Issue by Rob-Hudson** [mlytle4218/pod-kast-rust#6]
A useful feature to add would be:
number 0: download all episodes

Because if your podcast has episodes that scroll beyond the screen, you can only enter a range of numbers that are currently visible. For example, let's say your podcast has 40 episodes, and you want to download them all. When you first come to the episodes list, however, only episodes 1 through 20 are visible. And you can only enter that range.

It could also be useful to have the program confirm your selection. Something like
Downloading of episodes %x confirmed. Press enter to continue.

**Comment by mlytle4218** [comment]
Feature added. Pressing a will add all episodes to download list.
